### ISSUE TITLE
Преподаватель

### ISSUE THREAD

**Issue by YuriSilenok** [Students-of-the-city-of-Kostroma/Student-timetable#199]
1. Story:
   - [x] Model #195
   - Controller:
      - [x] new() #197
      - [x] Insert(Model model) #12 
      - [x] Update(Model model) #59  
      - [x] Delete(Model model) #18 
   - View:
      - [x] Select() #67 
      - [x] Insert(Model model) #66 
      - [x] Update(Model model) #194  
      - [x] Delete(Model model) #198 
2. Script:
3. Auto test:

**Comment by YuriSilenok** [comment]
Пожалуйста, добавьте веху к этой задаче

**Comment by YuriSilenok** [comment]
Пожалуйста, добавьте веху к этой задаче

**Comment by YuriSilenok** [comment]
Пожалуйста, добавьте веху к этой задаче

**Comment by YuriSilenok** [comment]
Пожалуйста, добавьте веху к этой задаче

**Comment by YuriSilenok** [comment]
Пожалуйста, добавьте веху к этой задаче

**Comment by YuriSilenok** [comment]
Пожалуйста, добавьте веху к этой задаче

**Comment by YuriSilenok** [comment]
Пожалуйста, добавьте веху к этой задаче
