### ISSUE TITLE
План на Sprint 4 - Альянс

### ISSUE THREAD

**Issue by Takunava** [Students-of-the-city-of-Kostroma/Student-timetable#759]
Задачи на спринт: 
- [x]  Добавить выбор Директора Института из существующих преподавателей #655
- [x] Исправить выбор ВУЗа из существующих ВУЗов #656
- [x]  Доработать таблицу сценариев #616 
- [x]  Восстановить табуляцию #697
- [x] Выполнить слияние Alliance-4 --> Testing  #752 
- [x] Исправить баги #726 #680 #685 #682 #230 #393 #678 #394 #684 #676 
- [x]  Исправить юнит-тесты #661
