### ISSUE TITLE
Этапы тестирования

### ISSUE THREAD

**Issue by nrabotko** [Students-of-the-city-of-Kostroma/Student-timetable#806]
План #769

- [x] Убрать клонирующие сценарии тестирования ( #784 )
- [x] Доработать сценарии тестирования ( #786 #785 #770 )
- [x] Провести мануальное тестирование ( #903 #904 #905 )
- [x] Дописать юнит-тесты (#897 #888 )

**Comment by nrabotko** [comment]
Все задачи выполнены.
